service: aws-utils

provider:
  name: aws
  runtime: ruby2.5
  region: ap-northeast-1
  stage: development

functions:
  resourceMacro:
    handler: handler.macro

resources:
  Resources:
    ResourceMacro:
      Type: AWS::CloudFormation::Macro
      Properties:
        Name: RMacro
        Description: Example macro
        FunctionName:
          Ref: ResourceMacroLambdaFunction
        LogGroupName: ResourceMacroLogGroup
        LogRoleARN:
          Ref: IamRoleLambdaExecution


